name: Handle Test Approvals

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  handle-test-approval:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && 
        (contains(github.event.comment.body, 'approve tests') || 
         contains(github.event.comment.body, 'regenerate tests'))) ||
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check for approval type
        id: check_approval
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            echo "action=approve" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.comment.body }}" == *"approve tests"* ]]; then
            echo "action=approve" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.comment.body }}" == *"regenerate tests"* ]]; then
            echo "action=regenerate" >> $GITHUB_OUTPUT
            requirements=$(echo "${{ github.event.comment.body }}" | sed -n 's/.*regenerate tests with \(.*\)/\1/p')
            echo "requirements=$requirements" >> $GITHUB_OUTPUT
          fi

      - name: Apply approved tests
        if: steps.check_approval.outputs.action == 'approve'
        run: |
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Ensure we're on the correct branch
          git fetch origin ${{ github.event.pull_request.head.ref || github.head_ref }}
          git checkout ${{ github.event.pull_request.head.ref || github.head_ref }}

          # Apply the stashed tests
          git stash pop || echo "No stashed changes found"

          # Commit and push if there are changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Apply approved tests"
            git push origin ${{ github.event.pull_request.head.ref || github.head_ref }}
          fi

      - name: Regenerate tests
        if: steps.check_approval.outputs.action == 'regenerate'
        run: |
          # Install dependencies
          npm ci

          # Run test generation with requirements if provided
          if [[ -n "${{ steps.check_approval.outputs.requirements }}" ]]; then
            npm run generate-tests -- "${{ steps.check_approval.outputs.requirements }}"
          else
            npm run generate-tests
          fi

          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Commit and push changes
          git add .
          git commit -m "Regenerate tests with provided requirements"
          git push origin ${{ github.event.pull_request.head.ref || github.head_ref }}