name: Approve Generated Tests

on:
  issue_comment:
    types: [created]

jobs:
  approve-tests:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, 'approve tests')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get PR and branch info
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const branch = pr.data.head.ref;
            core.setOutput('branch', branch);

      - name: Fetch test suggestion branch
        run: |
          git fetch origin test-suggestions-${{ steps.pr_info.outputs.branch }}

      - name: Merge generated tests
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout ${{ steps.pr_info.outputs.branch }}
          git merge origin/test-suggestions-${{ steps.pr_info.outputs.branch }} --no-edit
          git push origin ${{ steps.pr_info.outputs.branch }}

      - name: Comment to confirm merge
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Generated unit tests have been approved and merged into this PR.'
            });
